name: x86_64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: |
          cd file-win
          file.exe file.exe
